// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqr-IH9QW39oLnGiVGA6bqIXYm48E0TNo',
    appId: '1:983539101300:web:b5b0b42fdbd14c90986b21',
    messagingSenderId: '983539101300',
    projectId: 'e-commerce-4d004',
    authDomain: 'e-commerce-4d004.firebaseapp.com',
    storageBucket: 'e-commerce-4d004.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLFZdVZvuBSuw6qN3ptdknLTt7SU4Uxu0',
    appId: '1:983539101300:android:036a001b1a2c9e50986b21',
    messagingSenderId: '983539101300',
    projectId: 'e-commerce-4d004',
    storageBucket: 'e-commerce-4d004.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjdSD4geBVBLIFdWcd2BBQfdzD4i572QM',
    appId: '1:983539101300:ios:b12bc6737ba5f6c1986b21',
    messagingSenderId: '983539101300',
    projectId: 'e-commerce-4d004',
    storageBucket: 'e-commerce-4d004.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjdSD4geBVBLIFdWcd2BBQfdzD4i572QM',
    appId: '1:983539101300:ios:1c75aa0353f5c6a4986b21',
    messagingSenderId: '983539101300',
    projectId: 'e-commerce-4d004',
    storageBucket: 'e-commerce-4d004.appspot.com',
    iosBundleId: 'com.example.eCommerce.RunnerTests',
  );
}
